function layerMap = ReadLayerMap(fab, log)
%READLAYERMAP Load the layer map for a specific fabrication facility/process
%
%     ARGUMENT NAME     SIZE        DESCRIPTION
%     fab               'string'    Name of the fab & process
%
%     See also CASTSTRUCTURELAYER, CASTLAYERMAP, CASTDEFINEMAP, CASTPOSTPROCESSING.

log.write('\n\t%s  -  %s\n\n', log.title(), log.time());
log.write('\t\tLoading the layer map: %s\n', fab);

switch fab
  case 'general'
    layerMap = struct(...
      'FullCore', [1; 0],...
      'FullClad', [1; 1],...
      'FullHole', [1; 2],...
      'FullTrench', [1; 3],...
      'MidCore', [2; 0],...
      'MidClad', [2; 1],...
      'MidHole', [2; 2],...
      'MidTrench', [2; 3],...
      'ShallowCore', [3; 0],...
      'ShallowClad', [3; 1],...
      'ShallowHole', [3; 2],...
      'ShallowTrench', [3; 3],...
      'OxEtch', [7; 0],...
      'DeepEtch', [8; 0],...
      'NOTileSi', [9; 0],...
      ...
      'N', [11; 1],...
      'Np', [11; 2],...
      'Npp', [11; 3],...
      'P', [12; 1],...
      'Pp', [12; 2],...
      'Ppp', [12; 3],...
      'GeN', [13; 1],...
      'GeP', [14; 1],...
      ...
      'M1', [21; 1],...
      'M2', [21; 2],...
      'M3', [21; 3],...
      'M4', [21; 4],...
      'M5', [21; 5],...
      'V1', [22; 1],...
      'V2', [22; 2],...
      'V3', [22; 3],...
      'V4', [22; 4],...
      'V5', [22; 5],...
      'MOpen', [23; 1],...
      'NOTileM1', [29; 1],...
      'NOTileM2', [29; 2],...
      ...
      'Ge', [31; 0],...
      'PolyTrench', [32; 3],...
      'PolyInv', [32; 4],...
      'PolyFull', [32; 0],...
      'PolyMidCore', [33; 0],...
      'PolyMidClad', [33; 1],...
      'PolyMidHole', [33; 2],...
      'PolyMidTrench', [33; 3],...
      ...
      'FP', [91; 0],...
      'TXT', [92; 0],...
      'DRCexcl', [93; 0],...    
      'SEM', [94;0],...
      'FullCore6nmSPF', [103;0],...
      'FullCore4nm', [103;1],...
      'FullCore2nm', [103;2],...
      'FullTrench2nm', [103;3]);
  
  otherwise
    error('There is no layer map for that fabrication facility');
    
end